import re

MAX_FILE_SIZE = 10 * 1024 * 1024  # 10MB

# Blocked keywords for SQLite safety checks
BLOCKED_SQL_KEYWORDS = re.compile(
    r"\b(drop|delete|update|insert|create|alter|truncate|replace|grant|revoke|schema|exec|execute|attach|detach|load_extension)\b",
    re.IGNORECASE
)

def validate_file_extension(filename: str) -> bool:
    """Verifies that the file is a CSV or Excel spreadsheet."""
    if not filename:
        return False
    lower_name = filename.lower()
    return lower_name.endswith(".csv") or lower_name.endswith(".xlsx") or lower_name.endswith(".xls")

def validate_file_size(size_bytes: int) -> bool:
    """Verifies that the file size is within the allowed limit (10MB)."""
    return size_bytes <= MAX_FILE_SIZE

def validate_sql_query(query: str) -> tuple[bool, str]:
    """
    Validates a SQL query generated by AI.
    Ensures:
    1. It is a read-only SELECT query.
    2. No write or destructive commands are embedded.
    Returns:
        (is_valid, error_message)
    """
    if not query:
        return False, "Query is empty."
        
    trimmed_query = query.strip()
    
    # Check if query starts with SELECT (ignoring leading whitespace/comments)
    # Remove leading comments
    query_no_comments = re.sub(r"(--[^\n]*\n)|(/\*.*?\*/)", "", trimmed_query, flags=re.DOTALL).strip()
    
    if not query_no_comments.upper().startswith("SELECT"):
        return False, "Dangerous query structure detected: query must start with a SELECT statement."
        
    # Check for blocked keywords
    match = BLOCKED_SQL_KEYWORDS.search(query_no_comments)
    if match:
        return False, f"Dangerous SQL keyword detected: '{match.group(1)}' operations are blocked for safety."
        
    # Check for stacked/multiple queries (semicolon followed by another statement)
    # Allow a trailing semicolon, but block semicolons in the middle followed by statements
    semicolons = [m.start() for m in re.finditer(r";", query_no_comments)]
    if semicolons:
        # If there's a semicolon, verify nothing non-whitespace follows it
        for idx in semicolons:
            remaining = query_no_comments[idx+1:].strip()
            if remaining:
                return False, "Stacked queries (multiple SQL statements) are blocked for safety."
                
    return True, ""
